sudo: false
language: node_js
node_js:
  - "stable"
  - 4.2
  - 0.12
  - 0.10
  - 0.8

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.8"

notifications:
  email:
    - charlie.robbins@gmail.com

